# Generated by Django 5.2.5 on 2025-08-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_quixattempt_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.CharField(
                choices=[
                    ("A", "Option A"),
                    ("B", "Option B"),
                    ("C", "Option C"),
                    ("D", "Option D"),
                ],
                max_length=1,
            ),
        ),
    ]
